version: '2'

services:

  web:
    image: mycargus/hello_docker_world:latest
    environment:
      VIRTUAL_HOST: hello.docker

  testrunner:
    build:
      context: .
    environment:
      APP_HOST: hello.docker
      HUB_HOST: selenium.hub.docker
    volumes:
      - .:/usr/src/app
    links:
      - web
      - hub

  hub:
    image: selenium/hub:2.53.1
    environment:
      VIRTUAL_HOST: selenium.hub.docker
    ports:
      - "4444:4444"

  node-firefox:
    image: selenium/node-firefox:2.53.1
    environment:
      # this is a necessary workaround due to a known bug
      # https://github.com/SeleniumHQ/docker-selenium/issues/133
      HUB_PORT_4444_TCP_ADDR: hub
    links:
      - hub
      - web

  node-chrome:
    image: selenium/node-chrome:2.53.1
    environment:
      # this is a necessary workaround due to a known bug
      # https://github.com/SeleniumHQ/docker-selenium/issues/133
      HUB_PORT_4444_TCP_ADDR: hub
    links:
      - hub
      - web

  node-chrome-debug:
    image: selenium/node-chrome-debug:2.53.1
    environment:
      # this is a necessary workaround due to a known bug
      # https://github.com/SeleniumHQ/docker-selenium/issues/133
      HUB_PORT_4444_TCP_ADDR: hub
    ports:
      - "5900:5900"
    links:
      - hub
      - web

  node-firefox-debug:
    image: selenium/node-firefox-debug:2.53.1
    environment:
      # this is a necessary workaround due to a known bug
      # https://github.com/SeleniumHQ/docker-selenium/issues/133
      HUB_PORT_4444_TCP_ADDR: hub
    ports:
      - "5901:5900"
    links:
      - hub
      - web
